apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      role: rabbit
  template:
    metadata:
      labels:
        role: rabbit
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15692
          name: prometheus
          protocol: TCP
      initContainers:
      - command:
        - sh
        - -c
        - cp /tmp/rabbitmq/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf && echo '' >>
          /etc/rabbitmq/rabbitmq.conf; cp /tmp/rabbitmq/enabled_plugins /etc/rabbitmq/enabled_plugins
        image: busybox:1.32.0
        imagePullPolicy: IfNotPresent
        name: rabbitmq-config
        volumeMounts:
        - mountPath: /tmp/rabbitmq
          name: rabbitmq-config
        - mountPath: /etc/rabbitmq
          name: rabbitmq-config-rw
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
          name: rabbitmq-config
        name: rabbitmq-config
      - emptyDir: {}
        name: rabbitmq-config-rw
      - emptyDir: {}
        name: rabbitmq-data
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
