apiVersion: apps/v1
kind: Deployment
metadata:
  name: receptionist
spec:
  replicas: 2
  selector:
    matchLabels:
      role: receptionist
  template:
    metadata:
      labels:
        role: receptionist
    spec:
      containers:
      - name: receptionist
        image: tp2_ej3_receptionist
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 20
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
