apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-receptionist-deployment.yaml
- 02-worker-deployment.yaml
namespace: default
images:
- name: tp2_ej3_receptionist
  newName: agustinnormand/tp2_ej3_receptionist
  newTag: 191ad19e0d35f8a3826977943934cc6be9453baf
