apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-receptionist-deployment.yaml
- 02-worker-deployment.yaml
namespace: default
images:
- name: tp2_ej3_receptionist
  newName: agustinnormand/tp2_ej3_receptionist
  newTag: 34e11e19a3d0e59f46f718925d223822c0ad1938
