name: Publisher

on:
  push:
    paths:
    - 'TrabajoPractico2/Ejercicio_3/Codigo/Receptionist/**'
    - 'TrabajoPractico2/Ejercicio_3/Docker/Receptionist/**'

defaults:
  run:
    working-directory: TrabajoPractico2/Ejercicio_3/Codigo/Receptionist/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Build with Maven
        run:
          mvn clean package --file pom.xml
      - name: ls
        run: ls -R
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build and push Docker image
        working-directory: TrabajoPractico2/Ejercicio_3/Docker/Receptionist/
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: agustinnormand/tp2_ej3_receptionist:latest, agustinnormand/tp2_ej3_receptionist:${{ github.sha }}
        #with:
          # #path: 'TrabajoPractico2/Ejercicio_3/Codigo/Receptionist'
      # - name: Set up JDK 11
        # uses: actions/setup-java@v2
        # with:
          # java-version: '11'
          # distribution: 'adopt'
      # - name: Build with Maven
        # run: mvn --batch-mode --update-snapshots verify


# jobs:
  # build:
    # name: Build
    # runs-on: ubuntu-latest
    
    # steps:
    # - name: Set up Go 1.x
      # uses: actions/setup-go@v2
      # with:
        # go-version: ^1.14
      
    # - name: Check out code
      # uses: actions/checkout@v2

    # - name: Test
      # run: |
        # CGO_ENABLED=0 go test ./...
        
    # - name: Build and push Docker image
      # uses: docker/build-push-action@v1.1.0
      # with:
        # username: ${{ secrets.DOCKER_USERNAME }}
        # password: ${{ secrets.DOCKER_PASSWORD }}
        # repository: ${{ secrets.DOCKER_USERNAME }}/hello-gitops
        # tags: ${{ github.sha }}, latest

  # deploy:
    # name: Deploy
    # runs-on: ubuntu-latest
    # needs: build

    # steps:
    # - name: Check out code
      # uses: actions/checkout@v2

    # - name: Setup Kustomize
      # uses: imranismail/setup-kustomize@v1
      # with:
        # kustomize-version: "3.6.1"

    # - name: Update Kubernetes resources
      # env:
        # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      # run: |
      #  cd kustomize/base
      #  kustomize edit set image hello-gitops=$DOCKER_USERNAME/hello-gitops:$GITHUB_SHA
      #  cat kustomization.yaml
        
    # - name: Commit files
      # run: |
        # git config --local user.email "action@github.com"
        # git config --local user.name "GitHub Action"
        # git commit -am "Bump docker tag"
    # - name: Push changes
      # uses: ad-m/github-push-action@master
      # with:
        # github_token: ${{ secrets.GITHUB_TOKEN }}